const QUESTIONS = [
  {
    question: "What is the capital of France?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the capital of Japan.",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which city serves as the capital of Brazil?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the capital of Australia.",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the capital city of South Africa?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the capital of Italy.",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which city is the capital of Argentina?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the capital of Canada?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Identify the capital of China.",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the capital city of Russia.",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the capital of Mexico?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Which city serves as the capital of Egypt?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the capital of Germany.",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the capital city of Turkey?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the capital of India.",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which city is the capital of Nigeria?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the capital of South Korea?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Identify the capital of Saudi Arabia.",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the capital city of the United Kingdom?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the capital city of Pakistan?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the atomic number of hydrogen?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Which element has the symbol 'O'?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the atomic number of carbon?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the noble gas with atomic number 18.",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which element is essential for human bone structure?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the atomic symbol for gold?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the halogen with atomic number 17.",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which element is a noble gas with atomic number 10?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the element with atomic number 26.",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the symbol for the element sodium?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which element is a gas at room temperature?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Identify the element with atomic number 53.",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the atomic symbol for helium?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the element found in water with symbol H.",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which element is a metalloid with atomic number 14?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the atomic number of nitrogen?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the element used in pencils with atomic number 6.",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the element with atomic number 79.",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the symbol for the element with atomic number 92?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which element is commonly used in batteries?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the square root of 144?",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Calculate 8 + 5.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Subtract 17 from 25.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Multiply 6 by 9.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the result of 32 divided by 4?",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Calculate 3 squared.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Find the product of 7 and 11.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the sum of 14 and 19?",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Subtract 28 from 42.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Multiply 5 by 7.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Divide 45 by 9.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Calculate 2 cubed.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Find the difference between 15 and 8.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the product of 4 and 6?",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Subtract 37 from 50.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Multiply 8 by 3.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the sum of 23 and 16?",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Divide 63 by 9.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Calculate 11 squared.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Find the product of 9 and 7.",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Solve the equation: 2x + 5 = 15",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Find the solution to: 3y - 7 = 14",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Solve for x in the equation: 4x - 9 = 27",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the solution to: 2a + 8 = 20",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Find the value of x in the equation: 5x - 3 = 22",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Solve for y: 3y + 12 = 30",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Determine the solution to: 6z - 5 = 31",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Find the value of x in the equation: 2x - 4 = 10",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Solve for y: 4y + 9 = 33",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the solution to: 3p - 6 = 15",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Find the value of x in the equation: 5x + 7 = 42",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Solve for a: 2a - 10 = 18",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Determine the solution to: 3b + 15 = 30",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Find the value of x in the equation: 4x - 8 = 24",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Solve for y: 5y + 10 = 35",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the solution to: 2c - 7 = 11",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Find the value of x in the equation: 3x + 6 = 30",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Solve for z: 4z - 3 = 21",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Determine the solution to: 5w + 8 = 33",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Find the value of x in the equation: 2x + 9 = 25",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the principles of object-oriented programming.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Describe the concept of encapsulation in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Discuss the importance of inheritance in object-oriented programming.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Examine the role of polymorphism in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Elaborate on the concept of abstraction in object-oriented programming.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Discuss the advantages of using objects and classes in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the difference between a class and an object in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Describe the concept of method overloading in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Discuss the role of constructors in object-oriented programming.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Examine the concept of encapsulation and how it promotes data hiding.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Discuss the use of interfaces in achieving multiple inheritance in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Explain the importance of the 'this' keyword in object-oriented programming.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Discuss the concept of method overriding and its application in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "Examine the role of abstract classes in achieving abstraction in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Discuss the principles of OOP that contribute to code reusability.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the concept of dynamic polymorphism in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Discuss the role of access specifiers in OOP and their impact on encapsulation.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Examine the use of composition in object-oriented programming.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the concept of overloading operators in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the concept of static polymorphism in OOP.",
    subject: "Computer Science",
    topic: "OOP",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the largest ocean in the world?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Which ocean is the smallest among the five main oceans?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Identify the ocean that surrounds the North Pole.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the ocean that is located between Africa and Australia.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which ocean is known as the 'Pacific Ocean'?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the second-largest ocean in the world?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the ocean that separates Asia and North America.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Which ocean is characterized by the presence of the Antarctic Circumpolar Current?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Identify the ocean with the highest average depth.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the ocean that lies to the west of Europe.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which ocean is known for the Great Barrier Reef?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "Identify the ocean where the Mariana Trench, the deepest point on Earth, is located.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the ocean that has the highest salinity.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which ocean is bordered by the coasts of Brazil and Africa?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the ocean located to the south of Asia?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the ocean where the Gulf Stream flows.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the ocean that separates Australia and New Zealand.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which ocean is known for the phenomenon of El Niño?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the ocean located to the east of Africa?",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Identify the ocean where the North Equatorial Current flows.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the difference between a stack and a queue?",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the concept of time complexity in algorithms.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Describe the role of recursion in solving problems.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "What is the significance of Big-O notation in algorithm analysis?",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the advantages and disadvantages of using linked lists.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the concept of dynamic programming in algorithm design.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Describe the properties and applications of a binary search tree.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the importance of hashing in data structure design.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the concept of graph traversal in algorithms.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the role of a priority queue in algorithmic solutions?",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the applications of the breadth-first search algorithm.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "Explain the concept of divide and conquer in algorithmic design.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Describe the characteristics and uses of a heap data structure.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the role of a stack in algorithmic solutions.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Explain the concept of greedy algorithms and provide an example.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Describe the advantages and disadvantages of using arrays in algorithms.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the role of recursion in solving problems.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Explain the concept of time and space complexity in algorithm analysis.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Describe the applications of the depth-first search algorithm.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the role of a queue in algorithmic solutions.",
    subject: "Computer Science",
    topic: "Data Structures and Algorithms",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the process of photosynthesis?",
    subject: "Biology",
    topic: "Miscellaneous",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the difference between TCP and UDP?",
    subject: "Computer Science",
    topic: "Miscellaneous",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the theory of relativity.",
    subject: "Physics",
    topic: "Miscellaneous",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Discuss the impact of the Industrial Revolution on society.",
    subject: "History",
    topic: "Miscellaneous",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Examine the causes of climate change.",
    subject: "Environmental Science",
    topic: "Miscellaneous",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Compare and contrast classical and operant conditioning.",
    subject: "Psychology",
    topic: "Miscellaneous",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the Higgs boson and its significance?",
    subject: "Physics",
    topic: "Miscellaneous",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Discuss the ethical implications of genetic engineering.",
    subject: "Ethics",
    topic: "Miscellaneous",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Elaborate on the concept of manifest destiny in American history.",
    subject: "History",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Describe the structure and function of mitochondria.",
    subject: "Biology",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the concept of recursion in computer science.",
    subject: "Computer Science",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the chemical formula for water?",
    subject: "Chemistry",
    topic: "Miscellaneous",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the square root of 16?",
    subject: "Mathematics",
    topic: "Miscellaneous",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the difference between a monarchy and a republic?",
    subject: "Social Studies",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the meaning of the phrase 'in loco parentis'?",
    subject: "Latin",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the theory of relativity?",
    subject: "Physics",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the theory of evolution?",
    subject: "Biology",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the concept of quantum mechanics?",
    subject: "Physics",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the theory of continental drift?",
    subject: "Geology",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the theory of cognitive dissonance?",
    subject: "Psychology",
    topic: "Miscellaneous",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the name of the largest desert in the world?",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the name of the largest river in Africa?",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Identify the highest mountain in South America.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the longest river in Asia.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the driest desert in North America?",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which is the second-largest desert in Australia?",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Name the river known as the 'Cradle of Ancient Egyptian Civilization.'",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Identify the mountain range that spans seven countries in South Asia.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the largest river in Europe?",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the desert that spans parts of Mongolia and China.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the highest peak in North America.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the longest river in South America?",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the desert known as the 'Land of Five Waters.'",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the mountain range that separates Europe from Asia.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the name of the river that flows through Baghdad?",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Name the desert that spans parts of the United States and Mexico.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Identify the highest mountain in Africa.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the longest river in the world?",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the desert located in the southwestern United States.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Identify the mountain range that extends across Western North America.",
    subject: "Geography",
    topic: "Geographical Features",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the name of the largest moon of Saturn?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the name of the largest planet in our solar system?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Which celestial body is known as the Red Planet?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the closest star to Earth.",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the second-largest moon of Jupiter.",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the name of the dwarf planet farthest from the Sun?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which planet is known as the 'Evening Star' or 'Morning Star'?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the largest volcano in our solar system.",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which moon of Neptune is known for its retrograde orbit?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Identify the largest asteroid in the asteroid belt.",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "What is the name of the bright star in the center of the Orion constellation?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "Which moon of Uranus was discovered by William Herschel in 1787?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the spacecraft that first landed humans on the Moon.",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which gas is most abundant in the atmosphere of Venus?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the name of the largest canyon system on Mars?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Identify the moon of Pluto that is largest in size.",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which planet is known as the 'Blue Planet'?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the spacecraft that conducted the first flyby of Jupiter.",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "What is the name of the phenomenon where a celestial body temporarily obscures another?",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Identify the moon of Saturn that has prominent methane lakes.",
    subject: "Astronomy",
    topic: "Celestials",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the speed of light?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Define the concept of wavelength in the context of waves.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Explain the difference between transverse and longitudinal waves.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question:
      "What is the relationship between frequency and pitch in sound waves?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the properties of electromagnetic waves.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Define the term amplitude in the context of waves.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Explain the concept of wave interference.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the Doppler effect in wave phenomena?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Describe the formation of standing waves.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Explain the principle of wave reflection.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the significance of the wave equation?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Discuss the role of waves in the field of communication.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Explain the concept of wave diffraction.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Define the term phase in the context of wave oscillations.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Discuss the applications of ultrasonic waves in medical imaging.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the role of waves in the process of resonance?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the concept of wave polarization.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Discuss the phenomenon of wave refraction.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Define the term wave packet in the context of wave mechanics.",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the role of waves in the field of optics?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 5,
  },
];

module.exports = QUESTIONS;
